# Generated by Django 4.0.6 on 2022-07-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCli', models.AutoField(primary_key=True, serialize=False, verbose_name='Id cliente')),
                ('nomCli', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apeCli', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correoCli', models.EmailField(max_length=60, verbose_name='Correo electronico')),
                ('fonoCli', models.IntegerField(max_length=11, verbose_name='Telefono')),
                ('direccionCli', models.CharField(max_length=100, verbose_name='Direccion')),
            ],
        ),
    ]
