# Generated by Django 4.0.6 on 2022-07-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fonoCli',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
