# Generated by Django 4.0.6 on 2022-07-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_fonocli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idCon', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del contacto')),
                ('nomCon', models.TextField(max_length=50, verbose_name='Nombre')),
                ('apeCon', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correoCon', models.EmailField(max_length=60, verbose_name='Correo electronico')),
                ('fonoCon', models.IntegerField(verbose_name='Telefono')),
                ('motiCon', models.CharField(choices=[('c', 'consulta'), ('r', 'reclamo')], default='c', max_length=1)),
                ('comentCon', models.TextField(max_length=200, verbose_name='Comentarios')),
            ],
        ),
    ]
