# Generated by Django 4.0.6 on 2022-07-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nomCon',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
